### ISSUE TITLE
uimenu builde

### ISSUE THREAD

**Issue by Husseinovich** [douglashill/KeyboardKit#21]
Not issue

**Comment by douglashill** [comment]
I think the commands are not showing up because they conflict with the inputs of “Make Bigger” and “Make Smaller” in the default menu. This is how the KeyboardKit demo app solves this:

https://github.com/douglashill/KeyboardKit/blob/8e90bfd742af87994cfd2b6f3dea49a120e7ab6b/KeyboardKitDemo/AppDelegate.swift#L32-L34

For showing the inputs correctly to the user, this is how KeyboardKit solves it:

https://github.com/douglashill/KeyboardKit/blob/8e90bfd742af87994cfd2b6f3dea49a120e7ab6b/KeyboardKit/ScrollViewKeyHandler.swift#L55-L68

Hope this helps! I don’t think this is a problem with KeyboardKit so I’m going to close this issue.

**Comment by Husseinovich** [comment]
That was helpful. Thank you so much @douglashill
